
[tool.poetry]
package-mode = false

[project]
name = "ltu"
requires-python = ">=3.10"
dependencies = [
    "scp",
    "geographiclib",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
